### ISSUE TITLE
[Tracking] Models and Interfaces Issues

### ISSUE THREAD

**Issue by rkodev** [microsoftgraph/msgraph-sdk-typescript#96]
Tracking issue for all errors solved and fixed in the 

- [x] Additional Data is mandatory for data
- [x] microsoftgraph/microsoft-graph-devx-api#1011
- [x] microsoftgraph/microsoft-graph-devx-api#1012
- [x] microsoftgraph/microsoft-graph-devx-api#1015
- [ ] microsoftgraph/msgraph-sdk-typescript#100
- [x] microsoftgraph/msgraph-sdk-typescript#101
- [ ] microsoftgraph/microsoft-graph-devx-api#1014
- [x] microsoftgraph/microsoft-graph-devx-api#1013
- [x] microsoftgraph/msgraph-beta-sdk-typescript#11
- [ ] Add TS E2E tests to test uncompiled SDK
- [x] microsoftgraph/microsoft-graph-devx-api#1016
- [ ] microsoftgraph/msgraph-sdk-typescript#106
- [x] Fix Enum generation when sample Enum does not have a value
- [ ] microsoftgraph/msgraph-sdk-raptor#1083
- [x] microsoftgraph/msgraph-sdk-typescript#108

**Comment by baywet** [comment]
closing as most of the issues there are resolved, and the remaining once are not blocking a public preview
